#!/bin/bash

if [ ${BASH_VERSINFO[0]} -le 2 ]; then
  echo "[ERROR]: You must source this script (not run it in a sub-shell). Use like $ source genie_set_tune.sh <tune_id>"
  exit 1
fi


GENIE_XSEC_TUNE=${1}

if [ ! -e /opt/genie_xsec/${GENIE_VERSION}/${GENIE_XSEC_TUNE}/gxspl-min.xml.gz ]; then
  echo "Do not have inputs for tune ${GENIE_XSEC_TUNE}. Consider using /opt/genie/utils/genie_fetch_tune.sh to grab the tune."
  return 1
fi

export GENIE_XSEC_TUNE
export GENIE_XSEC_DIR=/opt/genie_xsec/${GENIE_VERSION}/${GENIE_XSEC_TUNE}
export GENIE_XSEC_FILE="${GENIE_XSEC_DIR}/gxspl-min.xml.gz"
export GENIE_PHYOPT_DIR=/opt/genie_phyopt/${GENIE_VERSION}/dkcharmtau

export GXMLPATH=${GENIE_PHYOPT_DIR}:${GENIE_XSEC_DIR}

echo "Set GENIE tune environment for version ${GENIE_VERSION}:"
echo -e "\t GENIE_XSEC_TUNE: ${GENIE_XSEC_TUNE}"
echo -e "\t  GENIE_XSEC_DIR: ${GENIE_XSEC_DIR}"
echo -e "\t GENIE_XSEC_FILE: ${GENIE_XSEC_FILE}"
echo -e "\tGENIE_PHYOPT_DIR: ${GENIE_PHYOPT_DIR}"
echo -e "\t        GXMLPATH: ${GXMLPATH}"